name: flutter_application_2
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

# Version and build number.
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.1 # Latest version
  cupertino_icons: ^1.0.8 # Latest stable version
  socket_io_client: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting rules
  flutter_lints: 5.0.0 # Updated from 5.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Uncomment and add your assets if needed
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Uncomment and add custom fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
